stages:
    - test
    - prepare
    - release
    - compatibility

include:
    -   template: Security/Secret-Detection.gitlab-ci.yml


#-----------------------------------------


.common: &common
    tags:
        - shell
    rules:
        -   if: $CI_COMMIT_TAG
            when: on_success
        -   if: $CI_COMMIT_BRANCH == "main"
            when: on_success
        -   if: $CI_COMMIT_BRANCH == "dev"
            when: on_success
    interruptible: true

.make_links: &make_links
    before_script:
        - export TAG=$(date '+%Y.%m.%d')
        - printenv
        - >
            if [ $(uname) == "Darwin" ]; then
            	sed -i '' "s/PACKAGE_VERSION/${TAG}/g" ./back/package.json
            	sed -i '' "s/PACKAGE_VERSION/${TAG}/g" front/package.json
            else
            	sed -i "s/PACKAGE_VERSION/${TAG}/g" back/package.json
            	sed -i "s/PACKAGE_VERSION/${TAG}/g" front/package.json
            fi


#-----------------------------------------


eslint:
    stage: test
    interruptible: true
    image: registry.gitlab.com/pipeline-components/eslint:latest
    script:
        - cd back
        - eslint --color .


#-----------------------------------------


prepare:
    <<: *common
    <<: *make_links
    stage: prepare
    image: node:alpine
    script:
        - cd front
        - pnpm install --prod --frozen-lockfile
        - pnpm run build
        - ./changelog.js ./dist/webdb/changelog.html
    artifacts:
        paths:
            - ./front/dist/webdb/


#-----------------------------------------


docker:
    <<: *common
    <<: *make_links
    dependencies:
        - prepare
    stage: release
    image: docker:latest
    variables:
        IMAGE_NAME: webdb/app
    script:
        - cp -fr ./front/dist/webdb/* ./back/static/
        - cd back
        - docker login -u 'aleluff' -p $DOCKER_PASS
        - docker buildx create --use
        - >
            if [ "$CI_COMMIT_REF_NAME" == "main" ]; then
                docker buildx build --cache-from $IMAGE_NAME:$CI_COMMIT_REF_NAME --platform linux/arm64,linux/amd64 --sbom=true --provenance=true -t $IMAGE_NAME:$CI_COMMIT_REF_NAME -t $IMAGE_NAME:$TAG -t $IMAGE_NAME --push .
            else
                docker buildx build --cache-from $IMAGE_NAME:$CI_COMMIT_REF_NAME --platform linux/arm64,linux/amd64 --sbom=true --provenance=true -t $IMAGE_NAME:$CI_COMMIT_REF_NAME --push .
            fi


#-----------------------------------------


compatibility:
    <<: *common
    stage: compatibility
    image: docker:latest
    script:
        - cd compatibility
        - npm install --prod --frozen-lockfile
        - npm run launch:webdb
        - sleep 3
        - npm run test:app
        - npm run test:docker || echo
    artifacts:
        paths:
            - ./compatibility/report.xml
