stages:
    - test
    - release

image: node:lts-alpine

eslint:
    stage: test
    interruptible: true
    script:
        - cd back
        - npm i
        - ./node_modules/.bin/eslint . || true

.release: &releases
    rules:
        -   if: $CI_COMMIT_TAG
        -   if: $CI_COMMIT_BRANCH == "main"
        -   if: $CI_COMMIT_BRANCH == "dev"
    stage: release
    interruptible: true
    before_script:
        - apk add git
        - sed -i "s/PACKAGE_VERSION/$CI_COMMIT_BRANCH-$(git rev-list --count HEAD)/g" **/package.json

#exe:
#    <<: *releases
#    script:
#        - npm i
#        - npm run exe

docker:
    <<: *releases
    variables:
        IMAGE_PATH: webdb/app:$CI_COMMIT_REF_NAME
        REGISTRY_IMAGE: webdb/app
    image: docker:latest
    services:
        - docker:dind
    script:
        - echo $IMAGE_PATH
#        - apk add curl
#        - curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
        - docker login -u 'webdb' -p $DOCKER_PASS
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull $IMAGE_PATH || true
        - docker build --cache-from "$IMAGE_PATH" --build-arg BRANCH_NAME=$CI_COMMIT_REF_NAME -t $IMAGE_PATH .
#        - docker scout cves "$IMAGE_PATH" -e --only-severity critical
        - '[[ $CI_COMMIT_REF_NAME == "main" ]] && docker tag $IMAGE_PATH $REGISTRY_IMAGE:latest && docker push $REGISTRY_IMAGE:latest'
        - docker push $IMAGE_PATH
