stages:
    - test
    - prepare
    - release
    - compatibility



#-----------------------------------------


.common: &common
    tags:
        - shell
    interruptible: true

.make_app: &make_app
    rules:
        -   changes:
                - front/**/*
                - back/**/*
            when: on_success
    before_script:
        - export TAG=$(date '+%Y.%m.%d')
        - printenv
        - >
            if [ $(uname) == "Darwin" ]; then
            	sed -i '' "s/PACKAGE_VERSION/${TAG}/g" ./back/package.json
            	sed -i '' "s/PACKAGE_VERSION/${TAG}/g" front/package.json
            else
            	sed -i "s/PACKAGE_VERSION/${TAG}/g" back/package.json
            	sed -i "s/PACKAGE_VERSION/${TAG}/g" front/package.json
            fi


#-----------------------------------------


eslint:
    stage: test
    interruptible: true
    image: registry.gitlab.com/pipeline-components/eslint:latest
    script:
        - (cd back && eslint --color .)
        - (cd compatibility && eslint --color .)
