stages:
    - test
    - release

include:
    - template: Security/Secret-Detection.gitlab-ci.yml

image: node:lts-alpine

eslint:
    stage: test
    interruptible: true
    script:
        - cd back
        - npm i
        - ./node_modules/.bin/eslint . || true

.release: &releases
    rules:
        -   if: $CI_COMMIT_TAG
        -   if: $CI_COMMIT_BRANCH == "main"
        -   if: $CI_COMMIT_BRANCH == "dev"
    stage: release
    interruptible: true
    before_script:
        - sed -i "s/PACKAGE_VERSION/$(date '+%y.%m.%d')/g" **/package.json

docker:
    <<: *releases
    variables:
        IMAGE_NAME: webdb/app
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
    image: docker:latest
    services:
        - docker:dind
    script:
        - printenv
        - |
            (
                apk add --no-cache --upgrade bash git &&
                cd front &&
                ./changeLog.sh 2d3cf36c03dfda72765ada56cea1310c6a58f139 > ./changelog.html
            )
        - docker login -u 'webdb' -p $DOCKER_PASS
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker buildx create --use
        - docker buildx build --cache-from $IMAGE_NAME:$CI_COMMIT_REF_NAME --platform linux/arm64,linux/amd64 -t $IMAGE_NAME:$CI_COMMIT_REF_NAME --push .
        - '[[ $CI_COMMIT_REF_NAME == "main" ]] && docker buildx build --cache-from $IMAGE_NAME:$CI_COMMIT_REF_NAME --platform linux/arm64,linux/amd64 -t $IMAGE_NAME --push .'
