stages:
    - test
    - prepare
    - release

include:
    - template: Security/Secret-Detection.gitlab-ci.yml

.common: &common
    rules:
        -   if: $CI_COMMIT_TAG
        -   if: $CI_COMMIT_BRANCH == "main"
        -   if: $CI_COMMIT_BRANCH == "dev"
    interruptible: true
    before_script:
        - printenv
        - sed -i "s/PACKAGE_VERSION/$(date '+%y.%m.%d')/g" back/package.json
        - sed -i "s/PACKAGE_VERSION/$(date '+%y.%m.%d')/g" front/package.json


#-----------------------------------------


eslint:
    stage: test
    image: registry.gitlab.com/pipeline-components/eslint:latest
    script:
        - cd back
        - eslint --color .


#-----------------------------------------


prepare:
    <<: *common
    stage: prepare
    image: node:alpine
    script:
        - apk add --no-cache --upgrade bash git
        - corepack enable && corepack prepare pnpm@latest --activate
        - cd front
        - pnpm install --prod --frozen-lockfile
        - pnpm run build
        - ./changeLog.sh 2d3cf36c03dfda72765ada56cea1310c6a58f139 > ./dist/webdb/changelog.html
    artifacts:
        paths:
            - ./front/dist/webdb/


#-----------------------------------------


binaries:
    rules:
        -   if: $CI_COMMIT_TAG
        -   if: $CI_COMMIT_BRANCH == "main"
        -   if: $CI_COMMIT_BRANCH == "dev"
    variables:
        TAG: "$(date '+%y.%m.%d')"
    interruptible: true
    before_script:
        - printenv
        - sed -i '' "s/PACKAGE_VERSION/${TAG}/g" back/package.json
        - sed -i '' "s/PACKAGE_VERSION/${TAG}/g" front/package.json
    dependencies:
        - prepare
    stage: release
    tags:
        - mbp
    script:
        - cp -fr ./front/dist/webdb/* ./back/src/front/
        - cd back
        - cp .env.production .env
        - npm install --frozen-lockfile
        - npm run obfuscate
        - npm run binaries:linux
        - npm run binaries:macos
        - >
            release-cli create
            --name "Release $TAG"
            --ref $CI_COMMIT_SHA
            --tag-name "$TAG"
            --assets-link '{"name":"WebDB-$TAG-arm64.dmg","url":"https://gitlab.com/web-db/app/-/jobs/$JOB_ID/artifacts/file/back/out/make/WebDB-$TAG-arm64.dmg"}'
            --assets-link '{"name":"WebDB-$TAG-x64.dmg","url":"https://gitlab.com/web-db/app/-/jobs/$JOB_ID/artifacts/file/back/out/make/WebDB-$TAG-x64.dmg"}'
            --assets-link '{"name":"webdb_$TAG_arm64.deb","url":"https://gitlab.com/web-db/app/-/jobs/$JOB_ID/artifacts/file/back/out/make/deb/arm64/webdb_$TAG_arm64.deb"}'
            --assets-link '{"name":"webdb_$TAG_x64.deb","url":"https://gitlab.com/web-db/app/-/jobs/$JOB_ID/artifacts/file/back/out/make/deb/arm64/webdb_$TAG_x64.deb"}'
    artifacts:
        paths:
            - ./back/out/make/

docker:
    <<: *common
    dependencies:
        - prepare
    stage: release
    variables:
        IMAGE_NAME: webdb/app
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
    image: docker:latest
    services:
        - docker:dind
    script:
        - cp -fr ./front/dist/webdb/* ./back/src/front/
        - rm ./back/src/shared/common-helper.mjs && cp common-helper.mjs ./back/src/shared/common-helper.mjs
        - cd back
        - docker login -u 'webdb' -p $DOCKER_PASS
        - docker buildx create --use
        - >
            if [ "$CI_COMMIT_REF_NAME" == "main" ]; then
                docker buildx build --cache-from $IMAGE_NAME:$CI_COMMIT_REF_NAME --platform linux/arm64,linux/amd64 -t $IMAGE_NAME:$CI_COMMIT_REF_NAME -t $IMAGE_NAME --push .
            else
                docker buildx build --cache-from $IMAGE_NAME:$CI_COMMIT_REF_NAME --platform linux/arm64,linux/amd64 -t $IMAGE_NAME:$CI_COMMIT_REF_NAME --push .
            fi
