version: '3.8'

services:

    mysql:
        image: mysql
        command: mysqld --default-authentication-plugin=mysql_native_password
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: notSecureChangeMe

    postgre:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

    mongo:
        image: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

#    sqldata:
#        image: mcr.microsoft.com/mssql/server:2017-latest
#        environment:
#            - SA_PASSWORD=Pass@word
#            - ACCEPT_EULA=Y
#        ports:
#            - "1433:1433"
#

#--------------------------------------------

#    mariadb:
#        image: mariadb
#        command: mysqld --default-authentication-plugin=mysql_native_password
#        ports:
#            - 3308:3306
#        environment:
#            MYSQL_ROOT_PASSWORD: notSecureChangeMe
#
#    cockroach:
#        image: cockroachdb/cockroach
#        command: start-single-node --insecure
#        ports:
#            - 26257:26257
#
#    tidb:
#
#    vitess

#--------------------------------------------

#    webdb:
#        image: webdb/app
#        ports:
#            - 22071:22071
#

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 4306:80
        environment:
            - PMA_ARBITRARY=1

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        ports:
            - 5050:80
