version: '3.8'

services:
    percona:
        image: percona
        restart: always
        ports:
            - '3317:3306'
        environment:
            MYSQL_ROOT_PASSWORD: notSecureChangeMe

    mysql:
        image: mysql
        command: mysqld --default-authentication-plugin=mysql_native_password
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: notSecureChangeMe

    postgre:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: notSecureChangeMe

    mongo:
        image: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: notSecureChangeMe

    cockroach:
        image: cockroachdb/cockroach
        command: start-single-node --insecure
        ports:
            - 26257:26257
        environment:
            COCKROACH_USER: 'root'
            COCKROACH_PASSWORD: 'notSecureChangeMe'
