version: '3.8'

services:

    mariadb:
        image: mariadb
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: notSecureChangeMe

    postgre:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: notSecureChangeMe

    mongo:
        image: mongo
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: notSecureChangeMe

    sqldata:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - MSSQL_SA_PASSWORD=yourStrong(!)Password
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"

    #Oracle
